//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> Interest { get; set; }
        public Nullable<double> Initial { get; set; }
        public Nullable<double> Deposit { get; set; }
        public Nullable<double> Withdraw { get; set; }
        public Nullable<double> DisplayBalance { get; set; }
    }
}
